before:
  hooks:
    - go mod tidy

builds:
  - id: premshow
    binary: premshow
    main: ./cmd/premshow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: premconfig
    binary: premconfig
    main: ./cmd/premconfig
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
  groups:
    - title: 'Breaking changes'
      regexp: '^.*?(\([[:word:]]+\))??!:.+$'
      order: 0
    - title: 'New features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other changes'
      regexp: '^.+$'
      order: 999